<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Document;
use App\Models\CyberAlert;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // Seed Documents
        $documents = [
            // Legal Documents
            ['title' => 'Information Technology Act, 2000', 'category' => 'legal', 'sub_category' => 'act', 'description' => 'The primary law in India dealing with cybercrime and electronic commerce. Contains provisions for digital signatures, electronic records, and cyber offences.', 'issued_by' => 'Ministry of Law and Justice', 'published_date' => '2000-06-09', 'reference_number' => 'IT-ACT-2000', 'file_size' => '2.4 MB', 'is_featured' => true, 'tags' => json_encode(['cybercrime', 'digital', 'IT'])],
            ['title' => 'IT (Amendment) Act, 2008', 'category' => 'legal', 'sub_category' => 'act', 'description' => 'Amendment to the IT Act 2000, introducing new provisions for cybercrime, data protection, and digital evidence.', 'issued_by' => 'Ministry of Law and Justice', 'published_date' => '2008-12-27', 'reference_number' => 'IT-AMEND-2008', 'file_size' => '1.8 MB', 'is_featured' => true, 'tags' => json_encode(['amendment', 'cybercrime', 'data'])],
            ['title' => 'Bharatiya Nyaya Sanhita (BNS) 2023', 'category' => 'legal', 'sub_category' => 'act', 'description' => 'The new criminal code replacing IPC, containing provisions for modern crimes including cybercrime and organized crime.', 'issued_by' => 'Ministry of Home Affairs', 'published_date' => '2023-12-25', 'reference_number' => 'BNS-2023', 'file_size' => '5.2 MB', 'is_featured' => true, 'tags' => json_encode(['BNS', 'criminal', 'code'])],
            ['title' => 'Bharatiya Nagarik Suraksha Sanhita (BNSS) 2023', 'category' => 'legal', 'sub_category' => 'act', 'description' => 'New code of criminal procedure replacing CrPC, modernizing investigation and trial procedures.', 'issued_by' => 'Ministry of Home Affairs', 'published_date' => '2023-12-25', 'reference_number' => 'BNSS-2023', 'file_size' => '4.8 MB', 'is_featured' => false, 'tags' => json_encode(['BNSS', 'procedure', 'investigation'])],
            ['title' => 'Bharatiya Sakshya Adhiniyam (BSA) 2023', 'category' => 'legal', 'sub_category' => 'act', 'description' => 'New evidence law replacing Indian Evidence Act, with updated provisions for electronic evidence.', 'issued_by' => 'Ministry of Law and Justice', 'published_date' => '2023-12-25', 'reference_number' => 'BSA-2023', 'file_size' => '3.1 MB', 'is_featured' => false, 'tags' => json_encode(['evidence', 'electronic', 'BSA'])],
            ['title' => 'Prevention of Money Laundering Act, 2002', 'category' => 'legal', 'sub_category' => 'act', 'description' => 'Law to prevent money laundering and provide for confiscation of property derived from money laundering.', 'issued_by' => 'Ministry of Finance', 'published_date' => '2002-01-17', 'reference_number' => 'PMLA-2002', 'file_size' => '1.9 MB', 'is_featured' => false, 'tags' => json_encode(['PMLA', 'money', 'laundering'])],
            ['title' => 'Personal Data Protection Bill, 2023', 'category' => 'legal', 'sub_category' => 'act', 'description' => 'Comprehensive data protection framework governing processing of digital personal data in India.', 'issued_by' => 'Ministry of Electronics and IT', 'published_date' => '2023-08-11', 'reference_number' => 'DPDP-2023', 'file_size' => '2.7 MB', 'is_featured' => true, 'tags' => json_encode(['data', 'privacy', 'DPDP'])],
            ['title' => 'Cyber Security Framework for Banks', 'category' => 'legal', 'sub_category' => 'rule', 'description' => 'RBI guidelines establishing comprehensive cybersecurity framework for banking institutions.', 'issued_by' => 'Reserve Bank of India', 'published_date' => '2024-01-15', 'reference_number' => 'RBI-CS-2024', 'file_size' => '3.3 MB', 'is_featured' => false, 'tags' => json_encode(['RBI', 'banking', 'security'])],

            // Government Circulars
            ['title' => 'Cyber Crime Reporting Guidelines 2024', 'category' => 'circular', 'sub_category' => 'advisory', 'description' => 'Updated guidelines for reporting cybercrime incidents to nodal police authorities and NCCRP portal.', 'issued_by' => 'Ministry of Home Affairs', 'published_date' => '2024-05-20', 'reference_number' => 'MHA/CYB/2024/001', 'file_size' => '1.2 MB', 'is_featured' => true, 'tags' => json_encode(['reporting', 'cybercrime', 'guidelines'])],
            ['title' => 'Digital Arrest Prevention Advisory', 'category' => 'circular', 'sub_category' => 'advisory', 'description' => 'Advisory to citizens and police departments about the fake digital arrest scam and how to counter it.', 'issued_by' => 'Ministry of Home Affairs', 'published_date' => '2024-05-18', 'reference_number' => 'MHA/CYB/2024/002', 'file_size' => '0.8 MB', 'is_featured' => true, 'tags' => json_encode(['digital arrest', 'fraud', 'advisory'])],
            ['title' => 'Social Media Monitoring Protocol', 'category' => 'circular', 'sub_category' => 'protocol', 'description' => 'Standard operating procedures for law enforcement monitoring of social media platforms for criminal activity.', 'issued_by' => 'Ministry of Home Affairs', 'published_date' => '2024-05-15', 'reference_number' => 'MHA/CYB/2024/003', 'file_size' => '1.5 MB', 'is_featured' => false, 'tags' => json_encode(['social media', 'monitoring', 'protocol'])],
            ['title' => 'BNS Section 318 Updated Guidelines', 'category' => 'circular', 'sub_category' => 'guideline', 'description' => 'Operational guidelines for implementing BNS Section 318 provisions in cybercrime investigations.', 'issued_by' => 'National Crime Records Bureau', 'published_date' => '2024-05-19', 'reference_number' => 'NCRB/BNS/2024/001', 'file_size' => '1.1 MB', 'is_featured' => false, 'tags' => json_encode(['BNS', 'Section 318', 'investigation'])],
            ['title' => 'IT Act Amendment 2024 Summary', 'category' => 'circular', 'sub_category' => 'summary', 'description' => 'Summary and implementation notes for police departments on IT Act amendments effective 2024.', 'issued_by' => 'Ministry of Electronics and IT', 'published_date' => '2024-05-17', 'reference_number' => 'MEITY/ITA/2024/001', 'file_size' => '0.9 MB', 'is_featured' => false, 'tags' => json_encode(['IT Act', 'amendment', '2024'])],
            ['title' => 'New Rules for Electronic Evidence', 'category' => 'circular', 'sub_category' => 'rule', 'description' => 'Updated procedures for collection, preservation, and presentation of electronic evidence in courts.', 'issued_by' => 'Ministry of Law and Justice', 'published_date' => '2024-05-14', 'reference_number' => 'MLJ/EE/2024/001', 'file_size' => '2.1 MB', 'is_featured' => false, 'tags' => json_encode(['evidence', 'electronic', 'court'])],
            ['title' => 'RBI Circular on Digital Payment Security', 'category' => 'circular', 'sub_category' => 'advisory', 'description' => 'Reserve Bank guidelines for security of digital payment systems and fraud prevention.', 'issued_by' => 'Reserve Bank of India', 'published_date' => '2024-04-30', 'reference_number' => 'RBI/DP/2024/001', 'file_size' => '1.7 MB', 'is_featured' => true, 'tags' => json_encode(['RBI', 'digital payment', 'security'])],

            // SOPs
            ['title' => 'SOP for FIR Registration in Cybercrime Cases', 'category' => 'sop', 'sub_category' => 'procedure', 'description' => 'Step-by-step procedure for registering FIR in cybercrime cases including jurisdiction and evidence documentation.', 'issued_by' => 'National Police Academy', 'published_date' => '2024-01-10', 'reference_number' => 'NPA/SOP/2024/001', 'file_size' => '1.4 MB', 'is_featured' => true, 'tags' => json_encode(['FIR', 'cybercrime', 'SOP'])],
            ['title' => 'SOP for Digital Forensic Investigation', 'category' => 'sop', 'sub_category' => 'forensics', 'description' => 'Standard procedures for digital forensic investigation, evidence collection and chain of custody.', 'issued_by' => 'Central Forensic Science Laboratory', 'published_date' => '2024-02-20', 'reference_number' => 'CFSL/SOP/2024/001', 'file_size' => '3.2 MB', 'is_featured' => true, 'tags' => json_encode(['forensics', 'digital', 'evidence'])],
            ['title' => 'SOP for Online Fraud Investigation', 'category' => 'sop', 'sub_category' => 'investigation', 'description' => 'Procedure for investigating online financial fraud, fund tracing, and suspect identification.', 'issued_by' => 'Cyber Crime Investigation Cell', 'published_date' => '2024-03-15', 'reference_number' => 'CCIC/SOP/2024/001', 'file_size' => '2.0 MB', 'is_featured' => false, 'tags' => json_encode(['online fraud', 'investigation', 'finance'])],
            ['title' => 'SOP for Social Media Crime Handling', 'category' => 'sop', 'sub_category' => 'procedure', 'description' => 'Guidelines for handling crimes committed via social media platforms including hate speech, harassment.', 'issued_by' => 'National Police Academy', 'published_date' => '2024-04-05', 'reference_number' => 'NPA/SOP/2024/002', 'file_size' => '1.6 MB', 'is_featured' => false, 'tags' => json_encode(['social media', 'crime', 'SOP'])],
        ];

        foreach ($documents as $doc) {
            Document::create($doc);
        }

        // Seed Cyber Alerts
        $alerts = [
            ['title' => 'Phishing Attack Alert - Government Portal Impersonation', 'description' => 'Threat actors are creating fake websites impersonating government portals to steal credentials and personal information from citizens.', 'severity' => 'critical', 'category' => 'phishing', 'source' => 'CERT-In', 'reference_id' => 'CERT-IN-2024-001', 'alert_date' => '2024-05-21', 'is_active' => true],
            ['title' => 'Fake Banking Apps Advisory', 'description' => 'Multiple fraudulent banking applications detected on third-party app stores. Citizens advised to download banking apps only from official sources.', 'severity' => 'high', 'category' => 'fraud', 'source' => 'RBI', 'reference_id' => 'RBI-ALERT-2024-001', 'alert_date' => '2024-05-20', 'is_active' => true],
            ['title' => 'Malware Distribution Warning - LockBit Variant', 'description' => 'New LockBit ransomware variant detected targeting government and financial institution networks. Immediate patching advised.', 'severity' => 'critical', 'category' => 'ransomware', 'source' => 'CERT-In', 'reference_id' => 'CERT-IN-2024-002', 'alert_date' => '2024-05-19', 'is_active' => true],
            ['title' => 'UPI Fraud Spike Alert', 'description' => 'Significant increase in UPI-based fraud cases reported. Victims lured via fake QR codes and payment links.', 'severity' => 'high', 'category' => 'fraud', 'source' => 'NPCI', 'reference_id' => 'NPCI-2024-001', 'alert_date' => '2024-05-18', 'is_active' => true],
            ['title' => 'SIM Swap Fraud Advisory', 'description' => 'Rise in SIM swap attacks targeting high-value bank account holders. Telecom providers and banks issued joint advisory.', 'severity' => 'high', 'category' => 'advisory', 'source' => 'DoT', 'reference_id' => 'DOT-2024-001', 'alert_date' => '2024-05-17', 'is_active' => true],
            ['title' => 'Investment Scam Campaign Detected', 'description' => 'Sophisticated investment scam using WhatsApp groups and Telegram channels promising high returns. Over 500 victims identified.', 'severity' => 'medium', 'category' => 'fraud', 'source' => 'SEBI', 'reference_id' => 'SEBI-2024-001', 'alert_date' => '2024-05-16', 'is_active' => true],
            ['title' => 'Critical Vulnerability in Apache Server', 'description' => 'Critical Remote Code Execution vulnerability discovered in Apache HTTP Server versions. Immediate patching recommended.', 'severity' => 'critical', 'category' => 'malware', 'source' => 'CERT-In', 'reference_id' => 'CERT-IN-2024-003', 'alert_date' => '2024-05-15', 'is_active' => true],
            ['title' => 'Digital Arrest Scam - New Variant', 'description' => 'New variant of digital arrest scam using fake CBI/ED officers impersonation via video calls. Citizens must be aware.', 'severity' => 'high', 'category' => 'fraud', 'source' => 'MHA', 'reference_id' => 'MHA-2024-001', 'alert_date' => '2024-05-14', 'is_active' => true],
            ['title' => 'Data Breach - Healthcare Sector', 'description' => 'Personal health records of over 7 lakh patients potentially compromised in cyber attack on healthcare provider.', 'severity' => 'critical', 'category' => 'advisory', 'source' => 'CERT-In', 'reference_id' => 'CERT-IN-2024-004', 'alert_date' => '2024-05-13', 'is_active' => true],
            ['title' => 'Aadhaar Phishing Campaign', 'description' => 'Fraudulent emails and SMS messages claiming Aadhaar suspension, directing users to fake UIDAI portals.', 'severity' => 'medium', 'category' => 'phishing', 'source' => 'UIDAI', 'reference_id' => 'UIDAI-2024-001', 'alert_date' => '2024-05-12', 'is_active' => true],
            ['title' => 'Job Offer Scam on Social Media', 'description' => 'Surge in job offer fraud targeting youth on social media, collecting personal documents and advance fees.', 'severity' => 'medium', 'category' => 'fraud', 'source' => 'I4C', 'reference_id' => 'I4C-2024-001', 'alert_date' => '2024-05-10', 'is_active' => true],
            ['title' => 'Spyware in Fake Government App', 'description' => 'Spyware disguised as official government app detected. App steals SMS, contacts, and location data.', 'severity' => 'high', 'category' => 'malware', 'source' => 'CERT-In', 'reference_id' => 'CERT-IN-2024-005', 'alert_date' => '2024-05-08', 'is_active' => true],
        ];

        foreach ($alerts as $alert) {
            CyberAlert::create($alert);
        }
    }
}
